name: CI
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|@github-actions-bot|dependabot\[bot\])
          avatarSize: 42

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-->'
          closeDelimiter: '<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-END-->'
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Modify contributors.ejs
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: template/contributors.ejs
          openDelimiter: '<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-->'
          closeDelimiter: '<!--AUTO_GENERATED_PLEASE_DONT_DELETE_IT-END-->'
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build Linux Command
        run: |
          npm install
          npm run build
          cp CONTRIBUTORS.svg .deploy

      - name: Deploy
        env:
          # 将生成的HTML站点数据推送至指定Github仓库
          GITHUB_REPO: github.com/muggledy/linux_command_html
        run: |
          git clone -b master "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" ./.deploy_git
          shopt -s extglob
          rm -rf ./.deploy_git/!(.|..|.git) && cp -r ./.deploy/* ./.deploy_git/ && cd ./.deploy_git
          git config user.name "muggledy" && git config user.email "zgjsycfndy2015@163.com"
          git add -A
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
          cd ../ && rm -rf ./.deploy_git
